# Generated by Django 4.0.10 on 2024-05-23 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kupon',
            name='kupon_sayisi',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='kupon',
            name='yatirialan',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='match',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='Coach',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='new_page.coach'),
        ),
        migrations.AddField(
            model_name='post',
            name='match_tag',
            field=models.ManyToManyField(to='new_page.match'),
        ),
    ]
