# Generated by Django 4.0.10 on 2024-05-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_page', '0002_kupon_kupon_sayisi_kupon_yatirialan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='minumum_bet_amount',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
