# Generated by Django 4.0.10 on 2024-05-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_page', '0003_match_minumum_bet_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='kupon',
            name='Match',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='kupon',
            name='kazanc',
            field=models.FloatField(default=1),
        ),
    ]
